# Generated by Django 5.2.6 on 2025-11-07 18:43

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sigla", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "cargo",
            },
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("jira_id", models.PositiveIntegerField(null=True)),
                ("jira_key", models.CharField(blank=True, default="", max_length=50)),
                ("nome", models.CharField(max_length=100)),
                ("data_criacao", models.DateField(auto_now_add=True)),
                (
                    "orcamento_previsto",
                    models.DecimalField(
                        decimal_places=2, default=20000.0, max_digits=15
                    ),
                ),
            ],
            options={
                "db_table": "projeto",
            },
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("time", models.CharField(blank=True, max_length=100)),
                ("data_criacao", models.DateField(auto_now_add=True)),
                (
                    "valor_hora",
                    models.DecimalField(
                        decimal_places=2,
                        default=40.0,
                        help_text="Valor/hora do desenvolvedor (R$)",
                        max_digits=8,
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="relatorios.cargo",
                    ),
                ),
                (
                    "gerente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinados",
                        to="relatorios.funcionario",
                    ),
                ),
            ],
            options={
                "db_table": "funcionario",
            },
        ),
        migrations.CreateModel(
            name="TipoIssue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                (
                    "descricao",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                ("jira_id", models.PositiveIntegerField()),
                ("data_criacao", models.DateField(default=datetime.datetime.now)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relatorios.projeto",
                    ),
                ),
            ],
            options={
                "db_table": "tipo_issue",
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("jira_id", models.PositiveIntegerField()),
                ("jira_key", models.CharField(max_length=50)),
                ("titulo", models.CharField(max_length=255)),
                ("criado_em", models.DateTimeField(null=True)),
                (
                    "tempo_gasto_seconds",
                    models.PositiveIntegerField(default=0, null=True),
                ),
                (
                    "tempo_estimado_seconds",
                    models.PositiveIntegerField(default=0, null=True),
                ),
                ("atualizado_em", models.DateTimeField(null=True)),
                ("status", models.CharField(blank=True, default="", max_length=100)),
                (
                    "funcionario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="relatorios.funcionario",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relatorios.projeto",
                    ),
                ),
                (
                    "tipo_issue",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="relatorios.tipoissue",
                    ),
                ),
            ],
            options={
                "db_table": "issue",
            },
        ),
    ]
