# Generated by Django 5.2.6 on 2025-09-16 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='ControleHorasEquipeResumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dev', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_projeto', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'db_table': 'controle_horas_equipe_resumo',
            },
        ),
        migrations.CreateModel(
            name='MetaTempoControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_clt', models.CharField(blank=True, max_length=100)),
                ('objetivo_estagirario', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'meta_tempo_controle',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'projeto',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('time', models.CharField(blank=True, max_length=100)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='relatorios.cargo')),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='relatorios.funcionario')),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.CreateModel(
            name='TempoGastoEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=10)),
                ('dia_mes', models.PositiveIntegerField()),
                ('mes', models.DateField()),
                ('tempo_gasto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.funcionario')),
                ('meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relatorios.metatempocontrole')),
            ],
            options={
                'db_table': 'controle_tempo_equipe',
            },
        ),
        migrations.CreateModel(
            name='TempoControleValores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizado_equipe', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_real', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_meta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('aproveitamento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('controle_tempo_equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.tempogastoequipe')),
            ],
            options={
                'db_table': 'controle_tempo_resumo',
            },
        ),
        migrations.CreateModel(
            name='ControleHorasEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('resumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relatorios.controlehorasequiperesumo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.funcionario')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.projeto')),
            ],
            options={
                'db_table': 'controle_horas_equipe',
                'unique_together': {('mes', 'projeto', 'funcionario')},
            },
        ),
    ]
