# Generated by Django 5.2.6 on 2025-09-12 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='ControleHorasEquipeResumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dev', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_projeto', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'db_table': 'controle_horas_equipe_values',
            },
        ),
        migrations.CreateModel(
            name='MetaTempoControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_ci', models.CharField(blank=True, db_column='goal_ci', max_length=100)),
                ('goal_estrategico', models.CharField(blank=True, db_column='goal_estrategico', max_length=100)),
            ],
            options={
                'db_table': 'time_control_goal',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'projeto',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('time', models.CharField(blank=True, max_length=100)),
                ('gerente', models.BooleanField(default=False)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='relatorios.cargo')),
            ],
            options={
                'db_table': 'func',
            },
        ),
        migrations.CreateModel(
            name='TempoGastoEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(db_column='dia_sem', max_length=10)),
                ('dia_mes', models.PositiveIntegerField(db_column='dia_mes')),
                ('mes', models.DateField()),
                ('tempo_gasto', models.DecimalField(db_column='tempo_gasto', decimal_places=2, max_digits=6)),
                ('funcionario', models.ForeignKey(db_column='id_func', on_delete=django.db.models.deletion.CASCADE, to='relatorios.funcionario')),
                ('meta', models.ForeignKey(blank=True, db_column='time_control_goal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='relatorios.metatempocontrole')),
            ],
            options={
                'db_table': 'time_control_spend_equipe',
            },
        ),
        migrations.CreateModel(
            name='TempoControleValores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizado_equipe', models.DecimalField(db_column='realizado_equipe', decimal_places=2, max_digits=6)),
                ('total_real', models.DecimalField(db_column='total_real', decimal_places=2, max_digits=6)),
                ('total_meta', models.DecimalField(db_column='total_meta', decimal_places=2, max_digits=6)),
                ('aproveitamento', models.DecimalField(db_column='aproveitamento', decimal_places=2, max_digits=5)),
                ('tempo_gasto', models.ForeignKey(db_column='id_time_control_spend_equipe', on_delete=django.db.models.deletion.CASCADE, to='relatorios.tempogastoequipe')),
            ],
            options={
                'db_table': 'time_control_CH_values',
            },
        ),
        migrations.CreateModel(
            name='ControleHorasEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('resumo', models.ForeignKey(blank=True, db_column='values_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='relatorios.controlehorasequiperesumo')),
                ('funcionario', models.ForeignKey(db_column='func_id', on_delete=django.db.models.deletion.CASCADE, to='relatorios.funcionario')),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.CASCADE, to='relatorios.projeto')),
            ],
            options={
                'db_table': 'controle_horas_equipe',
                'unique_together': {('mes', 'projeto', 'funcionario')},
            },
        ),
    ]
