# Generated by Django 5.2.6 on 2025-11-07 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControleHorasEquipeResumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_dev",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "total_projeto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
            ],
            options={
                "db_table": "controle_horas_equipe_resumo",
            },
        ),
        migrations.CreateModel(
            name="MetaTempoControle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objetivo_clt", models.CharField(blank=True, max_length=100)),
                ("objetivo_estagiario", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "meta_tempo_controle",
            },
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="jira_key",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="tipoissue",
            name="descricao",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name="TempoGastoEquipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia_semana", models.CharField(max_length=10)),
                ("dia_mes", models.PositiveIntegerField()),
                ("mes", models.DateField()),
                ("tempo_gasto", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relatorios.funcionario",
                    ),
                ),
                (
                    "meta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="relatorios.metatempocontrole",
                    ),
                ),
            ],
            options={
                "db_table": "controle_tempo_equipe",
            },
        ),
        migrations.CreateModel(
            name="TempoControleValores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "realizado_equipe",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("total_real", models.DecimalField(decimal_places=2, max_digits=6)),
                ("total_meta", models.DecimalField(decimal_places=2, max_digits=6)),
                ("aproveitamento", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "controle_tempo_equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relatorios.tempogastoequipe",
                    ),
                ),
            ],
            options={
                "db_table": "controle_tempo_resumo",
            },
        ),
        migrations.CreateModel(
            name="ControleHorasEquipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.DateField()),
                (
                    "horas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relatorios.funcionario",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relatorios.projeto",
                    ),
                ),
                (
                    "resumo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="relatorios.controlehorasequiperesumo",
                    ),
                ),
            ],
            options={
                "db_table": "controle_horas_equipe",
                "unique_together": {("mes", "projeto", "funcionario")},
            },
        ),
        migrations.AddConstraint(
            model_name="tempogastoequipe",
            constraint=models.UniqueConstraint(
                fields=("funcionario", "dia_mes", "mes"),
                name="unique_funcionario_dia_mes",
            ),
        ),
    ]
