"""Classe de migração para renomear campo em MetatempoControle."""
#pylint: disable=line-too-long
# Generated by Django 5.2.6 on 2025-09-22 02:49

from django.db import migrations


class Migration(migrations.Migration):
    """Renomeia o campo objetivo_estagirario para objetivo_estagiario."""
    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metatempocontrole',
            old_name='objetivo_estagirario',
            new_name='objetivo_estagiario',
        ),
    ]
