# Generated by Django 5.2.6 on 2025-09-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_rename_objetivo_estagirario_metatempocontrole_objetivo_estagiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='horas_previstas',
            field=models.FloatField(default=0),
        ),
    ]
