# Generated by Django 5.2.6 on 2025-10-17 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0003_funcionario_valor_hora"),
        ("relatorios", "0003_tempogastoequipe_unique_funcionario_dia_mes"),
    ]

    operations = []
