# Generated by Django 5.2.6 on 2025-10-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0004_merge_20251017_0018"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="orcamento_previsto",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddConstraint(
            model_name="projeto",
            constraint=models.CheckConstraint(
                condition=models.Q(("orcamento_previsto__gte", 20000.0)),
                name="orcamento_previsto_min_20000",
            ),
        ),
    ]
