# Generated by Django 5.2.6 on 2025-11-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0005_projeto_orcamento_previsto_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="projeto",
            name="orcamento_previsto_min_20000",
        ),
        migrations.AlterField(
            model_name="projeto",
            name="orcamento_previsto",
            field=models.DecimalField(decimal_places=2, default=20000.0, max_digits=15),
        ),
    ]
