# Generated by Django 5.2.6 on 2025-11-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0006_remove_projeto_orcamento_previsto_min_20000_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="jira_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="projeto",
            name="jira_key",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
