# Generated by Django 5.2.6 on 2025-11-06 02:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0007_projeto_jira_id_projeto_jira_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="TipoIssue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.CharField(blank=True, max_length=1024, null=True)),
                ("jira_id", models.PositiveIntegerField()),
                ("data_criacao", models.DateField(default=datetime.datetime.now)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relatorios.projeto",
                    ),
                ),
            ],
            options={
                "db_table": "tipo_issue",
            },
        ),
    ]
