# Generated by Django 5.2.6 on 2025-11-06 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0008_alter_projeto_id_tipoissue"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("jira_id", models.PositiveIntegerField()),
                ("jira_key", models.CharField(max_length=50)),
                ("titulo", models.CharField(max_length=255)),
                ("criado_em", models.DateTimeField(null=True)),
                (
                    "tempo_gasto_seconds",
                    models.PositiveIntegerField(default=0, null=True),
                ),
                (
                    "tempo_estimado_seconds",
                    models.PositiveIntegerField(default=0, null=True),
                ),
                ("atualizado_em", models.DateTimeField(null=True)),
                ("status", models.CharField(max_length=100, null=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="relatorios.funcionario",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relatorios.projeto",
                    ),
                ),
                (
                    "tipo_issue",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="relatorios.tipoissue",
                    ),
                ),
            ],
            options={
                "db_table": "issue",
            },
        ),
    ]
