# Generated by Django 5.2.6 on 2025-11-07 17:03

from django.db import migrations, models


def fill_blank_strings(apps, schema_editor):
    Projeto = apps.get_model("relatorios", "Projeto")
    TipoIssue = apps.get_model("relatorios", "TipoIssue")
    Issue = apps.get_model("relatorios", "Issue")

    Projeto.objects.filter(jira_key__isnull=True).update(jira_key="")
    TipoIssue.objects.filter(descricao__isnull=True).update(descricao="")
    Issue.objects.filter(status__isnull=True).update(status="")


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0009_issue"),
    ]

    operations = [
        migrations.RunPython(fill_blank_strings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="jira_key",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="tipoissue",
            name="descricao",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
    ]
