services:
  web:
    container_name: django-app
    image: ruthmira/minha-app:latest
    env_file:
      - .env
    command: >
      sh -c "
        python manage.py migrate --database=default --noinput &&
        python manage.py migrate --database=olap --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn config.wsgi:application --workers 4 --bind 0.0.0.0:8000
      "
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    ports:
      - "8000:8000"
    restart: always

  cron:
    container_name: django-cron
    image: ruthmira/minha-app:latest
    env_file:
      - .env
    user: root
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Removendo crontab antigo...' &&
        python manage.py crontab remove || true &&
        echo 'Adicionando crontab...' &&
        python manage.py crontab add &&
        echo 'Cron iniciado em: $(date)' >> /app/log/cron.log &&
        cron -f
      "
    restart: always
