services:
  web:
    container_name: django-app
    image: ruthmira/minha-app:latest
    env_file:
      - .env
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        su appuser -c 'gunicorn config.wsgi:application --workers 4 --bind 0.0.0.0:8000'
      "
    ports:
      - "8000:8000"
    restart: always

  cron:
    container_name: django-cron
    image: ruthmira/minha-app:latest
    env_file:
      - .env
    user: root
    command: >
      sh -c "
        service cron start &&
        python manage.py crontab remove &&
        python manage.py crontab add &&
        tail -f /app/log/cron_buscar_dados_api.log
      "
    volumes:
      - .:/app
    restart: always
