# Identificação do projeto
sonar.projectKey=AthosFatecSjc_server
sonar.organization=athosfatecsjc
sonar.host.url=https://sonarcloud.io

# Versão do Python
sonar.python.version=3.11

# Diretórios de código fonte
sonar.sources=apps,config,olap_models

# Diretórios de testes
sonar.tests=tests
sonar.test.inclusions=**/tests/**,**/test_*.py

# Ignorar arquivos e pastas geradas automaticamente ou que não são código-fonte
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/banco/**,**/banco/**/*.sql,**/banco/**/*.py,**/banco/*.sql,**/banco/*.py,**/static/**,**/templates/**,**/venv/**,**/log/**

# Ignorar também esses arquivos nas métricas de cobertura e code smells
sonar.coverage.exclusions=**/migrations/**,**/__pycache__/**,**/banco/**,**/banco/**/*.sql,**/banco/**/*.py,**/banco/*.sql,**/banco/*.py,**/static/**,**/templates/**,**/venv/**,**/log/**
sonar.issue.exclusions=**/migrations/**,**/__pycache__/**,**/banco/**,**/banco/**/*.sql,**/banco/**/*.py,**/banco/*.sql,**/banco/*.py,**/static/**,**/templates/**,**/venv/**,**/log/**
