# Generated by Django 5.2.6 on 2025-11-11 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_create_default_users"),
        ("usuarios", "0002_seed_default_users"),
    ]

    operations = []
