name: PR Validation

on:
  pull_request:
    branches: [ "develop", "release" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Analisar Código com Pylint (Django)
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          SECRET_KEY: fake-key
        run: |
          pip install pylint pylint-django
          pylint --django-settings-module=config.settings $(git ls-files '*.py')

      - name: Verificação de Segurança com Bandit
        run: |
          pip install bandit
          bandit -r . -f json -o bandit-report.json || echo "Bandit encontrou problemas"

      - name: Executar Testes e Gerar Cobertura
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          TEST_DB_ENGINE: django.db.backends.sqlite3
          TEST_DB_NAME: ":memory:"
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        run: |
          pip install coverage
          coverage run --source='.' manage.py test
          coverage xml

      - name: Análise no SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload do Relatório de Cobertura
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Upload do Relatório de Segurança (Bandit)
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json
