# Generated by Django 5.2.6 on 2025-10-23 19:49

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olap_models", "0003_fatoregistrohoras_custo_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="FatoCustoFuncionarioProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_horas_trabalhadas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "custo_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
            ],
            options={
                "db_table": "fato_custo_funcionario_projeto",
            },
        ),
        migrations.RenameField(
            model_name="dimfuncionario",
            old_name="nome_funcionario",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="dimprojeto",
            old_name="nome_projeto",
            new_name="nome",
        ),
        migrations.RemoveField(
            model_name="dimfuncionario",
            name="gerente",
        ),
        migrations.RemoveField(
            model_name="dimtempo",
            name="dia_do_mes",
        ),
        migrations.RemoveField(
            model_name="dimtempo",
            name="nome_mes",
        ),
        migrations.AddField(
            model_name="dimfuncionario",
            name="nome_gerente",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="dimtempo",
            name="dia",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="dimtempo",
            name="hora",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
            ),
        ),
        migrations.AddField(
            model_name="dimtempo",
            name="mes_nome",
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="dimfuncionario",
            name="cargo",
            field=models.CharField(default="dev", max_length=20),
        ),
        migrations.AlterField(
            model_name="dimfuncionario",
            name="data_contratacao",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="dimfuncionario",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="dimprojeto",
            name="data_criacao",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="dimprojeto",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="dimtempo",
            name="ano",
            field=models.IntegerField(
                default=1900,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dimtempo",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="dimtempo",
            name="mes",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="dimtempo",
            constraint=models.CheckConstraint(
                condition=models.Q(("hora__gte", 0), ("hora__lte", 23)),
                name="hora_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dimtempo",
            constraint=models.CheckConstraint(
                condition=models.Q(("dia__gte", 1), ("dia__lte", 31)),
                name="dia_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dimtempo",
            constraint=models.CheckConstraint(
                condition=models.Q(("mes__gte", 1), ("mes__lte", 12)),
                name="mes_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dimtempo",
            constraint=models.CheckConstraint(
                condition=models.Q(("ano__gte", 1900), ("ano__lte", 2026)),
                name="ano_range_valid",
            ),
        ),
        migrations.AddField(
            model_name="fatocustofuncionarioprojeto",
            name="data_id",
            field=models.ForeignKey(
                db_column="data_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="olap_models.dimtempo",
            ),
        ),
        migrations.AddField(
            model_name="fatocustofuncionarioprojeto",
            name="funcionario_id",
            field=models.ForeignKey(
                db_column="funcionario_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="olap_models.dimfuncionario",
            ),
        ),
        migrations.AddField(
            model_name="fatocustofuncionarioprojeto",
            name="projeto_id",
            field=models.ForeignKey(
                db_column="projeto_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="olap_models.dimprojeto",
            ),
        ),
        migrations.AddConstraint(
            model_name="fatocustofuncionarioprojeto",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_horas_trabalhadas__gte", 0)),
                name="total_horas_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fatocustofuncionarioprojeto",
            constraint=models.CheckConstraint(
                condition=models.Q(("custo_total__gte", 0)),
                name="custo_total_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fatocustofuncionarioprojeto",
            constraint=models.UniqueConstraint(
                fields=("funcionario_id", "projeto_id", "data_id"),
                name="unique_fato_per_day",
            ),
        ),
    ]
