# Generated by Django 5.2.6 on 2025-11-04 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olap_models", "0004_rename_nome_funcionario_dimfuncionario_nome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatoregistrohoras",
            name="data",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="olap_models.dimtempo",
            ),
        ),
        migrations.AlterField(
            model_name="fatoregistrohoras",
            name="funcionario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="olap_models.dimfuncionario",
            ),
        ),
        migrations.AlterField(
            model_name="fatoregistrohoras",
            name="projeto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="olap_models.dimprojeto",
            ),
        ),
    ]
