# Generated by ChatGPT - Add issue fields to FatoRegistroHoras
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olap_models", "0005_alter_fatoregistrohoras_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fatoregistrohoras",
            name="issue_type",
            field=models.CharField(max_length=30, null=True, blank=True, db_index=True),
        ),
        migrations.AddField(
            model_name="fatoregistrohoras",
            name="issue_key",
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="fatoregistrohoras",
            name="issue_summary",
            field=models.CharField(max_length=200, null=True, blank=True),
        ),
    ]
